/**
 * Static post pages (generated by scripts/generate-posts.mjs)
 *
 * Each post has its own indexable page: real <title>, canonical, Open Graph and
 * BlogPosting JSON-LD, and the writing list links to it.
 */
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const SLUG = 'lidar-gait-analysis-iphone';

test('writing cards link to the post pages', async ({ page }) => {
    await page.goto('/');
    const link = page.locator(`#blog-posts a[href="/posts/${SLUG}/"]`);
    await expect(link).toBeVisible();
    await link.click();
    await page.waitForURL(`**/posts/${SLUG}/`);
    await expect(page.locator('h1')).toBeVisible();
});

test('post page has its own metadata and structured data', async ({ page }) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));

    await page.goto(`/posts/${SLUG}/`);

    await expect(page).toHaveTitle(/On-Device Gait Analysis.* \| Matthew Anderson/);
    await expect(page.locator('h1')).toHaveCount(1);
    await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
        'href',
        `https://andernet.dev/posts/${SLUG}/`
    );
    await expect(page.locator('meta[property="og:type"]')).toHaveAttribute('content', 'article');

    const ld = JSON.parse(await page.locator('script[type="application/ld+json"]').textContent());
    expect(ld['@type']).toBe('BlogPosting');
    expect(ld.url).toBe(`https://andernet.dev/posts/${SLUG}/`);

    expect(errors).toEqual([]);
});

test('post page navigation: back link, pager, theme toggle', async ({ page }) => {
    await page.goto(`/posts/${SLUG}/`);

    // Newer and older neighbours
    await expect(page.locator('.post-pager-link')).toHaveCount(2);

    const toggle = page.locator('#theme-toggle');
    const before = await page.evaluate(() => document.body.classList.contains('dark-theme'));
    await toggle.click();
    await expect
        .poll(() => page.evaluate(() => document.body.classList.contains('dark-theme')))
        .toBe(!before);

    await page.locator('.blog-back-link').click();
    await page.waitForURL('**/#writing');
    await expect(page.locator('#writing')).toBeVisible();
});

test('post page has no axe violations', async ({ page }) => {
    await page.goto(`/posts/${SLUG}/`);
    const results = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
        .exclude('iframe[src*="cloudflare"]')
        .analyze();
    expect(results.violations).toEqual([]);
});
