/**
 * Build icons/sprite.svg from Font Awesome Free (devDependency).
 *
 * Only the icons listed below ship. Ids keep the names the markup already used
 * (e.g. "external-link-alt"), mapped to FA 6's canonical file names. Every symbol
 * is padded to a square viewBox so `width: 1em; height: 1em` renders every icon at
 * the size the old icon font did. Run with `pnpm build:icons` after editing ICONS.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const FA_DIR = fileURLToPath(
  new URL('../node_modules/@fortawesome/fontawesome-free/svgs/', import.meta.url)
);
const OUT = fileURLToPath(new URL('../icons/sprite.svg', import.meta.url));

// id -> [style, FA 6 file name]
const solid = (file, id) => [id ?? file, ['solid', file]];
const ICONS = Object.fromEntries([
  ['github', ['brands', 'github']],
  ['linkedin', ['brands', 'linkedin']],
  solid('arrow-left'),
  solid('arrow-right'),
  solid('arrow-up'),
  solid('bolt'),
  solid('book-open'),
  solid('briefcase'),
  solid('calendar'),
  solid('calendar-days', 'calendar-alt'),
  solid('circle-dot'),
  solid('circle-plus', 'plus-circle'),
  solid('clock'),
  solid('code'),
  solid('code-branch'),
  solid('code-commit'),
  solid('code-pull-request'),
  solid('gear', 'cog'),
  solid('gears', 'cogs'),
  solid('envelope'),
  solid('eye'),
  solid('file-lines', 'file-alt'),
  solid('file-pdf'),
  solid('globe'),
  solid('graduation-cap'),
  solid('location-dot', 'map-marker-alt'),
  solid('magnifying-glass', 'search'),
  solid('magnifying-glass-plus', 'search-plus'),
  solid('moon'),
  solid('paper-plane'),
  solid('pen'),
  solid('spinner'),
  solid('star'),
  solid('sun'),
  solid('tag'),
  solid('up-right-from-square', 'external-link-alt'),
  solid('xmark', 'times'),
]);

const symbols = Object.entries(ICONS)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, [style, file]]) => {
    const svg = readFileSync(`${FA_DIR}${style}/${file}.svg`, 'utf8');
    const [, w, h] = svg.match(/viewBox="0 0 (\d+) (\d+)"/).map(Number);
    const path = svg.match(/<path d="([^"]+)"/)[1];
    const size = Math.max(w, h);
    const viewBox = `${(w - size) / 2} ${(h - size) / 2} ${size} ${size}`;
    return `  <symbol id="${id}" viewBox="${viewBox}"><path d="${path}"/></symbol>`;
  });

writeFileSync(
  OUT,
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n<!-- Generated by scripts/build-icons.mjs from Font Awesome Free 6.5.1 (CC BY 4.0, https://fontawesome.com/license/free) -->\n${symbols.join('\n')}\n</svg>\n`
);
console.log(`Wrote ${symbols.length} icons to icons/sprite.svg`);
